# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true
    - name: login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
    - name: Build docker image
      run: docker build -t sunilya96/testing_docker_ec2:latest .
    - name: publish image to docker hub
      run: docker push sunilya96/testing_docker_ec2

deploy:
    needs: build
    runs-on: [aws_ec2]
    steps:
    - name: pull the image from docker hub
      run: docker pull sunilya96/testing_docker_ec2:latest


      -name: removing all none images
      run: docker image prune -f

    - name: Stop & remove old container if exists
      run: |
        docker ps -a --format '{{.Names}}' | grep -w springboot-app >/dev/null 2>&1 && \
          docker stop springboot-app || true
        docker ps -a --format '{{.Names}}' | grep -w springboot-app >/dev/null 2>&1 && \
          docker rm springboot-app || true

    - name: Run the new container
      
      run: run -p 8081:8080 --name Springboot-app --network mynetwork --link mymongo:mongo -d sunilya96/testing_docker_ec2:latest
    

